---
author:
  - name: Sidney Verba
    url: https://en.wikipedia.org/wiki/Sidney_Verba
    phone: 123456789
    email: "example@harvard.edu"
    degrees:
      - PhD
    affiliations:
      - name: Harvard University
        department: Department of Government
    title: "Carl H. Pforzheimer University Professor (Emeritus)"
date: today
format:
  cv-typst: default
---

## Using this template


The goal of this template is to combine Quarto's best features with typst's best to get a cv powered by shortcodes.
For the best exerience, you will want to combine shortcodes with text in Quarto.
The shortcodes will format standard entries, but do not cover all possible cases.
As such, you may want to format some things using `typst` blocks or any other Quarto inputs.
This template was designed by [Christopher T. Kenny](https://christophertkenny.com/).

## Shortcodes

This template is made of a base template and a shortcode, `{{{ cv type file }}}`.

- type: points to one of the supported shortcode types below
- file: points to a file with a field with the same title as `type`

This allows you to get the full benefits from Quarto, while having sensible formatting options.
Notably, these fill from a yaml file (or a series of them).

The supported shortcodes types are:

- appointments: for academic appointment information
- education: for education history


## Appointments

{{< cv appointments education.yaml >}}

## Education

{{< cv education >}}



## Other tips: Tables work

Here, we can see that you can use text or a tables if included functions are insufficient.

| rank     | package  |   count  |
| -------: | :------- | -------: |
|     1    |    rlang |  1672290 |
|     2    |  ggplot2 |  1624767 |
|     3    |      cli |  1389491 |
|     4    |     Rcpp |  1386753 |
|     5    |    dplyr |  1361177 |
